# Dataset Section:
# url: URL to download the dataset (hosted on Google Drive).
# download: Path where the downloaded zip file will be saved.
# zip_path: Path where the dataset will be extracted.
# extract_to: Path where the dataset will be extracted.
# DFP: The DataFrame path after extraction (CSV file).
# target: The target column in the dataset for prediction (diagnosis).

# Model Section:
# model_path_s: Path where the pre-trained model is saved.
# path_model: Specific path to the model file (gradient_boosting.pkl).

# Preprocess Section:
# drop_columns: Columns to drop from the dataset.
# drop_duplicates: Whether to drop duplicate rows.
# drop_outliers: Whether to drop outliers.
# missing_columns: Columns that may contain missing data.
# missing_method: Method to handle missing data (mean imputation).
# scaler_method: Method to scale the data (minmax scaling).
# scaler_columns: List of columns to scale.
# encoder_columns: Columns to apply encoding to (diagnosis).
# method: Encoding method (currently set to None).
# replce: Whether to replace values in the dataset (set to True).
# value_replce: Dictionary specifying values to replace (e.g., {'M': 1, 'B': 0} for encoding diagnosis).

dataset:
  url: "https://drive.google.com/file/d/1gCvzRbsBtPT-u1LinpEesTfN5YkjzXNn/view?usp=sharing"
  download: "/home/alrashidissa/Desktop/BreastCancer/Dataset/downloads"
  name_dataset: "brestcancerset"
  zip_path: "/home/alrashidissa/Desktop/BreastCancer/Dataset/downloads/brestcancerset.zip"
  extract_to: "/home/alrashidissa/Desktop/BreastCancer/Dataset/extract"
  DFP: "/home/alrashidissa/Desktop/BreastCancer/Dataset/extract/breast-cancer.csv"
  target: "diagnosis"
  data_version: "1.0.0"

model:
  name_model: "GradientBoostingModel"
  model_path_s: "/home/alrashidissa/Desktop/BreastCancer/PreTrainModel"
  path_model: "/home/alrashidissa/Desktop/BreastCancer/PreTrainModel/gradient_boosting.pkl"

preprocess:
  handling: None
  handl_missing: False
  fill_value: None
  drop_columns: ["id"]
  drop_duplicates: True
  drop_outliers: True
  missing_columns: ["None"]
  missing_method: "mean"
  scaler_method: "minmax"
  scaler_columns:
    - "radius_mean"
    - "texture_mean"
    - "perimeter_mean"
    - "area_mean"
    - "smoothness_mean"
    - "compactness_mean"
    - "concavity_mean"
    - "concave points_mean"
    - "symmetry_mean"
    - "fractal_dimension_mean"
    - "radius_se"
    - "texture_se"
    - "perimeter_se"
    - "area_se"
    - "smoothness_se"
    - "compactness_se"
    - "concavity_se"
    - "concave points_se"
    - "symmetry_se"
    - "fractal_dimension_se"
    - "radius_worst"
    - "texture_worst"
    - "perimeter_worst"
    - "area_worst"
    - "smoothness_worst"
    - "compactness_worst"
    - "concavity_worst"
    - "concave points_worst"
    - "symmetry_worst"
    - "fractal_dimension_worst"
  encoder_columns: ["diagnosis"]
  method_encoder: None
  replce: True
  value_replce:
    M: 1
    B: 0
  fill_na: False
  plotes_pathes: "/home/alrashidissa/Desktop/BreastCancer/Plots"

mlflow:
  tage_name: "BCCV2"
  tage_value: "V2"
  tage_description: "This model predicts breast cancer using a."
  google_api_key: ""
